import { controlStyle, buttonStyle } from '../theme/tokens.js';
export const GRID_COLUMNS = 12;

const styles = {
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: 'var(--bg)',
        color: 'var(--text)',
        fontFamily: "'Inter', -apple-system, sans-serif",
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
    },
    // Kept deliberately flat: this strip carries a title and two status
    // readouts, and every pixel it takes is a pixel the columns below lose.
    header: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px 12px',
        flexWrap: 'wrap',
        borderBottom: '1px solid var(--border)',
        backgroundColor: 'var(--surface)',
        flexShrink: 0,
    },
    title: {
        fontSize: '12px',
        fontWeight: 700,
        color: 'var(--text)',
        fontFamily: "'JetBrains Mono', monospace",
        letterSpacing: '0.5px',
        margin: 0,
    },
    connectionDot: {
        width: 7,
        height: 7,
        borderRadius: '50%',
        marginLeft: 'auto',
    },
    connectionText: {
        fontSize: '11px',
        color: 'var(--muted)',
    },
    taskCount: {
        fontSize: '11px',
        color: 'var(--muted)',
        marginLeft: '4px',
    },
    bulkBar: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '5px 16px',
        backgroundColor: "var(--warning-soft)",
        borderBottom: "1px solid var(--warning)",
        flexShrink: 0,
        flexWrap: 'wrap',
    },
    bulkCount: {
        fontSize: '12px',
        fontWeight: 700,
        color: "var(--warning)",
    },
    bulkSelect: {
        fontSize: '12px',
        padding: '2px 6px',
        border: "1px solid var(--warning)",
        borderRadius: '4px',
        backgroundColor: 'var(--surface-raised)',
        cursor: 'pointer',
    },
    bulkMoveBtn: { ...controlStyle, ...buttonStyle('primary') },
    bulkClearBtn: { ...controlStyle, ...buttonStyle('default') },
    // Slim strip between header and board. flexShrink:0 keeps it from being
    // squeezed away by the flex:1 board below it.
    emptyHint: {
        flexShrink: 0,
        padding: '7px 20px',
        fontSize: '12px',
        lineHeight: 1.4,
        color: 'var(--muted)',
        backgroundColor: 'var(--surface)',
        borderBottom: '1px solid var(--border)',
    },
    board: {
        display: 'grid',
        // Keep even the narrow one-track columns usable in the side panel.
        // The board scrolls as a whole instead of clipping each column header.
        gridTemplateColumns: `repeat(${GRID_COLUMNS}, minmax(48px, 1fr))`,
        alignContent: 'start',
        flex: 1,
        gap: '4px',
        padding: '10px',
        overflow: 'auto',
        backgroundColor: 'var(--bg)',
    },
    column: {
        // The span comes from COLUMN_SPAN per column; minWidth:0 is what stops
        // a long task title from widening its column past its grid track and
        // pushing the row out of alignment.
        minWidth: 0,
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'var(--surface)',
        borderRadius: '8px',
        overflow: 'hidden',
        border: '1px solid var(--border)',
        maxHeight: '45vh',
    },
    columnCollapsed: {
        // Collapsed to its header only — it keeps its place in the row rather
        // than jumping to full width, so collapsing one column no longer
        // reshuffles the whole board.
        maxHeight: 'none',
        alignSelf: 'start',
    },
    columnHeader: {
        flexShrink: 0,
        display: 'flex',
        alignItems: 'center',
        gap: '4px',
        padding: '8px 7px',
        borderBottom: '1px solid var(--border)',
        backgroundColor: 'var(--surface-raised)',
    },
    columnDot: {
        width: 7,
        height: 7,
        borderRadius: '50%',
    },
    columnLabel: {
        fontSize: '11px',
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
        color: 'var(--text)',
    },
    columnCount: {
        marginLeft: 'auto',
        fontSize: '11px',
        color: 'var(--muted)',
        backgroundColor: 'rgba(148,163,184,0.12)',
        padding: '1px 5px',
        borderRadius: '8px',
    },
    cardList: {
        flex: 1,
        minHeight: 0,
        overflowY: 'auto',
        padding: '6px',
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    // Intent-Chips der Idee. Klein genug, dass drei davon plus Prio in die
    // schmale Spalte passen, ohne die Karte zu dominieren — die Idee selbst
    // bleibt die Hauptsache.
    intentChip: {
        ...controlStyle,
        border: '1px solid',
    },
    intentPriority: {
        ...controlStyle,
        '--control-height': '28px',
        '--control-padding': '4px 8px',
        '--control-font-size': '12px',
        border: '1px solid',
        cursor: 'pointer',
        marginLeft: 'auto',
        appearance: 'none',
        WebkitAppearance: 'none',
    },
    // Native options need explicit theme colours as well as the closed select.
    intentPriorityOption: {
        color: 'var(--text)',
        backgroundColor: 'var(--surface)',
        fontWeight: 400,
    },
    card: {
        flexShrink: 0,
        overflowWrap: 'anywhere',
        backgroundColor: 'var(--surface-raised)',
        borderRadius: '5px',
        padding: '8px 10px',
        border: '1px solid var(--border)',
        cursor: 'grab',
        transition: 'box-shadow 0.1s',
    },
    cardTop: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '3px',
    },
    cardId: {
        minWidth: 0,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontSize: '9px',
        color: 'var(--muted)',
        fontFamily: "'JetBrains Mono', monospace",
    },
    cardDelete: {
        marginLeft: 'auto',
        background: 'transparent',
        border: 'none',
        cursor: 'pointer',
        color: 'var(--muted)',
        fontSize: '14px',
        lineHeight: 1,
        padding: '0 2px',
        borderRadius: '3px',
    },
    confirmPanel: {
        width: '380px',
        maxWidth: 'calc(100vw - 24px)',
        boxSizing: 'border-box',
        backgroundColor: 'var(--surface-raised)',
        border: '1px solid var(--border)',
        borderRadius: '12px',
        padding: '20px',
        boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    },
    confirmTitle: {
        fontSize: '15px',
        fontWeight: 600,
        marginBottom: '12px',
    },
    confirmBody: {
        backgroundColor: 'var(--bg)',
        borderRadius: '6px',
        padding: '10px 12px',
        marginBottom: '12px',
    },
    confirmTaskTitle: {
        fontSize: '13px',
        fontWeight: 500,
        marginBottom: '4px',
    },
    confirmTaskId: {
        fontSize: '10px',
        color: 'var(--muted)',
        fontFamily: "'JetBrains Mono', monospace",
    },
    confirmNote: {
        fontSize: '12px',
        color: 'var(--muted)',
        lineHeight: 1.5,
        marginBottom: '16px',
    },
    confirmError: {
        fontSize: '12px',
        color: "var(--danger)",
        backgroundColor: "var(--danger-soft)",
        border: "1px solid var(--danger)",
        borderRadius: '6px',
        padding: '8px 10px',
        marginBottom: '12px',
    },
    confirmActions: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '8px',
    },
    confirmCancel: { ...controlStyle, ...buttonStyle('default') },
    confirmDelete: { ...controlStyle, ...buttonStyle('danger') },
    priorityBadge: {
        flexShrink: 0,
        whiteSpace: 'nowrap',
        fontSize: '9px',
        fontWeight: 700,
        padding: '1px 5px',
        borderRadius: '3px',
        color: "var(--text)",
        letterSpacing: '0.5px',
    },
    cardTitle: {
        fontSize: '13px',
        fontWeight: 500,
        lineHeight: 1.3,
        marginBottom: '3px',
        color: 'var(--text)',
    },
    cardDesc: {
        fontSize: '11px',
        color: 'var(--muted)',
        lineHeight: 1.4,
        marginBottom: '5px',
        display: '-webkit-box',
        WebkitLineClamp: 2,
        WebkitBoxOrient: 'vertical',
        overflow: 'hidden',
    },
    cardFooter: {
        display: 'flex',
        gap: '4px',
        flexWrap: 'wrap',
    },
    assignee: {
        fontSize: '10px',
        color: 'var(--text)',
        backgroundColor: 'var(--surface-raised)',
        padding: '1px 5px',
        borderRadius: '3px',
        paddingLeft: '5px',
    },
    category: {
        fontSize: '10px',
        color: "var(--violet)",
        backgroundColor: "var(--violet-soft)",
        padding: '1px 5px',
        borderRadius: '3px',
    },
    comment: {
        marginTop: '5px',
        fontSize: '10px',
        color: "var(--warning)",
        fontStyle: 'italic',
        padding: '3px 5px',
        backgroundColor: "var(--warning-soft)",
        borderRadius: '3px',
    },
    overlay: {
        position: 'fixed',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.3)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    detailPanel: {
        width: '600px',
        maxWidth: 'calc(100vw - 24px)',
        boxSizing: 'border-box',
        maxHeight: '80vh',
        backgroundColor: 'var(--surface-raised)',
        border: '1px solid var(--border)',
        borderRadius: '12px',
        padding: '24px',
        overflowY: 'auto',
        boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    },
    detailHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '12px',
    },
    detailId: {
        fontSize: '11px',
        color: 'var(--muted)',
        fontFamily: "'JetBrains Mono', monospace",
    },
    detailClose: {
        fontSize: '16px',
        color: 'var(--muted)',
        cursor: 'pointer',
        width: '26px',
        height: '26px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: '4px',
        backgroundColor: 'var(--surface-raised)',
    },
    detailTitle: {
        fontSize: '18px',
        fontWeight: 600,
        marginBottom: '12px',
        color: 'var(--text)',
    },
    detailMeta: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
        marginBottom: '20px',
        flexWrap: 'wrap',
    },
    detailStatus: {
        fontSize: '11px',
        color: "var(--info)",
        backgroundColor: 'rgba(3,105,161,0.1)',
        padding: '2px 8px',
        borderRadius: '3px',
        fontWeight: 600,
    },
    detailAssignee: {
        fontSize: '11px',
        color: "var(--warning)",
        backgroundColor: "var(--warning-soft)",
        padding: '2px 8px',
        borderRadius: '3px',
    },
    detailCategory: {
        fontSize: '11px',
        color: "var(--violet)",
        backgroundColor: "var(--violet-soft)",
        padding: '2px 8px',
        borderRadius: '3px',
    },
    detailSection: {
        marginBottom: '16px',
    },
    detailSectionLabel: {
        fontSize: '10px',
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '1px',
        color: 'var(--muted)',
        marginBottom: '8px',
    },
    detailDesc: {
        fontSize: '13px',
        lineHeight: 1.6,
        color: 'var(--text)',
        backgroundColor: 'var(--surface-raised)',
        padding: '12px',
        borderRadius: '6px',
        borderLeft: '2px solid var(--border)',
    },
    detailLoading: {
        textAlign: 'center',
        color: 'var(--muted)',
        padding: '40px',
    },
    nodeList: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    nodeItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 10px',
        backgroundColor: 'var(--surface-raised)',
        borderRadius: '4px',
        fontSize: '12px',
        flexWrap: 'wrap',
        border: '1px solid var(--border)',
    },
    nodeLabel: {
        fontSize: '9px',
        fontWeight: 700,
        color: "var(--violet)",
        backgroundColor: "var(--violet-soft)",
        padding: '1px 5px',
        borderRadius: '2px',
        textTransform: 'uppercase',
    },
    nodeName: {
        fontFamily: "'JetBrains Mono', monospace",
        color: 'var(--text)',
        fontWeight: 500,
    },
    nodeFile: {
        fontSize: '10px',
        color: 'var(--muted)',
    },
    lockBadge: {
        fontSize: '9px',
        padding: '1px 6px',
        borderRadius: '3px',
        marginLeft: 'auto',
        fontWeight: 600,
    },
    detailComment: {
        fontSize: '12px',
        color: "var(--warning)",
        backgroundColor: "var(--warning-soft)",
        padding: '8px 12px',
        borderRadius: '6px',
        fontStyle: 'italic',
    },
    commentAuthor: {
        fontWeight: 600,
        marginRight: '6px',
        fontStyle: 'normal',
        color: 'var(--text)',
    },
    // ── Detail actions / edit form ──
    detailActions: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
        marginBottom: '16px',
        paddingBottom: '14px',
        borderBottom: '1px solid var(--border)',
    },
    editBtn: { ...controlStyle, ...buttonStyle('default') },
    detailDeleteBtn: { ...controlStyle, ...buttonStyle('danger'), marginLeft: 'auto' },
    editLabel: {
        fontSize: '10px',
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '1px',
        color: 'var(--muted)',
        marginBottom: '5px',
        display: 'block',
    },
    editInput: {
        width: '100%',
        fontSize: '14px',
        fontFamily: 'inherit',
        padding: '8px 10px',
        borderRadius: '6px',
        border: '1px solid var(--border)',
        boxSizing: 'border-box',
        backgroundColor: 'var(--surface-raised)',
        color: 'var(--text)',
    },
    editTextarea: {
        width: '100%',
        fontSize: '13px',
        fontFamily: 'inherit',
        lineHeight: 1.5,
        padding: '8px 10px',
        borderRadius: '6px',
        border: '1px solid var(--border)',
        boxSizing: 'border-box',
        resize: 'vertical',
        backgroundColor: 'var(--surface-raised)',
        color: 'var(--text)',
    },
    editSaveBtn: { ...controlStyle, ...buttonStyle('primary') },
};

export default styles;
